## water body
'EVENT_ID', 'SOURCE', 'PROJECT', 'STATION', 'SAMPLE_DATE',
'SAMPLE_TIME', 'DEPTH', 'LAYER', 'SAMPLE_TYPE', 'SAMPLE_ID',
'PARAMETER', 'QUALIFIER', 'VALUE', 'UNIT', 'METHOD', 'LAB',
'PROBLEM', 'DETAILS', 'TOTAL_DEPTH', 'UPPER_PYCNOCLINE', 
'LOWER_PYCNOCLINE', 'LAT', 'LONG'